# coding: utf-8

"""
    Serge API

    API documentation for Serge server  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from serge_client.api_client import ApiClient


class DatabaseManagementApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def delete_db_get(self, db, **kwargs):  # noqa: E501
        """Delete a database  # noqa: E501

        Deletes a database specified by the query parameter  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_db_get(db, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str db: Name of the database to delete (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_db_get_with_http_info(db, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_db_get_with_http_info(db, **kwargs)  # noqa: E501
            return data

    def delete_db_get_with_http_info(self, db, **kwargs):  # noqa: E501
        """Delete a database  # noqa: E501

        Deletes a database specified by the query parameter  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_db_get_with_http_info(db, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str db: Name of the database to delete (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['db']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_db_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'db' is set
        if ('db' not in params or
                params['db'] is None):
            raise ValueError("Missing the required parameter `db` when calling `delete_db_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'db' in params:
            query_params.append(('db', params['db']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/deleteDb', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def download_all_get(self, **kwargs):  # noqa: E501
        """Download all databases  # noqa: E501

        Downloads all databases in a zip format  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.download_all_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.download_all_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.download_all_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def download_all_get_with_http_info(self, **kwargs):  # noqa: E501
        """Download all databases  # noqa: E501

        Downloads all databases in a zip format  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.download_all_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method download_all_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/zip'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/downloadAll', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='str',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def download_wargame_get(self, wargame, **kwargs):  # noqa: E501
        """Download wargame database  # noqa: E501

        Downloads a wargame database in zip format  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.download_wargame_get(wargame, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str wargame: Name of the SQLite file to download (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.download_wargame_get_with_http_info(wargame, **kwargs)  # noqa: E501
        else:
            (data) = self.download_wargame_get_with_http_info(wargame, **kwargs)  # noqa: E501
            return data

    def download_wargame_get_with_http_info(self, wargame, **kwargs):  # noqa: E501
        """Download wargame database  # noqa: E501

        Downloads a wargame database in zip format  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.download_wargame_get_with_http_info(wargame, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str wargame: Name of the SQLite file to download (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['wargame']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method download_wargame_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'wargame' is set
        if ('wargame' not in params or
                params['wargame'] is None):
            raise ValueError("Missing the required parameter `wargame` when calling `download_wargame_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'wargame' in params:
            path_params['wargame'] = params['wargame']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/zip'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/download/{wargame}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='str',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
