# coding: utf-8

"""
    Serge API

    API documentation for Serge server  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2007Data(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'other_properties_based_on_your_schema_': 'object'
    }

    attribute_map = {
        'id': '_id',
        'other_properties_based_on_your_schema_': '[ other properties based on your schema ]'
    }

    def __init__(self, id=None, other_properties_based_on_your_schema_=None):  # noqa: E501
        """InlineResponse2007Data - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._other_properties_based_on_your_schema_ = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if other_properties_based_on_your_schema_ is not None:
            self.other_properties_based_on_your_schema_ = other_properties_based_on_your_schema_

    @property
    def id(self):
        """Gets the id of this InlineResponse2007Data.  # noqa: E501


        :return: The id of this InlineResponse2007Data.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse2007Data.


        :param id: The id of this InlineResponse2007Data.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def other_properties_based_on_your_schema_(self):
        """Gets the other_properties_based_on_your_schema_ of this InlineResponse2007Data.  # noqa: E501


        :return: The other_properties_based_on_your_schema_ of this InlineResponse2007Data.  # noqa: E501
        :rtype: object
        """
        return self._other_properties_based_on_your_schema_

    @other_properties_based_on_your_schema_.setter
    def other_properties_based_on_your_schema_(self, other_properties_based_on_your_schema_):
        """Sets the other_properties_based_on_your_schema_ of this InlineResponse2007Data.


        :param other_properties_based_on_your_schema_: The other_properties_based_on_your_schema_ of this InlineResponse2007Data.  # noqa: E501
        :type: object
        """

        self._other_properties_based_on_your_schema_ = other_properties_based_on_your_schema_

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2007Data, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2007Data):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
