# coding: utf-8

"""
    Serge API

    API documentation for Serge server  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2006Data(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'wargame_title': 'str',
        'wargame_initiated': 'bool',
        'name': 'str'
    }

    attribute_map = {
        'id': '_id',
        'wargame_title': 'wargameTitle',
        'wargame_initiated': 'wargameInitiated',
        'name': 'name'
    }

    def __init__(self, id=None, wargame_title=None, wargame_initiated=None, name=None):  # noqa: E501
        """InlineResponse2006Data - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._wargame_title = None
        self._wargame_initiated = None
        self._name = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if wargame_title is not None:
            self.wargame_title = wargame_title
        if wargame_initiated is not None:
            self.wargame_initiated = wargame_initiated
        if name is not None:
            self.name = name

    @property
    def id(self):
        """Gets the id of this InlineResponse2006Data.  # noqa: E501


        :return: The id of this InlineResponse2006Data.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse2006Data.


        :param id: The id of this InlineResponse2006Data.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def wargame_title(self):
        """Gets the wargame_title of this InlineResponse2006Data.  # noqa: E501


        :return: The wargame_title of this InlineResponse2006Data.  # noqa: E501
        :rtype: str
        """
        return self._wargame_title

    @wargame_title.setter
    def wargame_title(self, wargame_title):
        """Sets the wargame_title of this InlineResponse2006Data.


        :param wargame_title: The wargame_title of this InlineResponse2006Data.  # noqa: E501
        :type: str
        """

        self._wargame_title = wargame_title

    @property
    def wargame_initiated(self):
        """Gets the wargame_initiated of this InlineResponse2006Data.  # noqa: E501


        :return: The wargame_initiated of this InlineResponse2006Data.  # noqa: E501
        :rtype: bool
        """
        return self._wargame_initiated

    @wargame_initiated.setter
    def wargame_initiated(self, wargame_initiated):
        """Sets the wargame_initiated of this InlineResponse2006Data.


        :param wargame_initiated: The wargame_initiated of this InlineResponse2006Data.  # noqa: E501
        :type: bool
        """

        self._wargame_initiated = wargame_initiated

    @property
    def name(self):
        """Gets the name of this InlineResponse2006Data.  # noqa: E501


        :return: The name of this InlineResponse2006Data.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse2006Data.


        :param name: The name of this InlineResponse2006Data.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2006Data, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2006Data):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
