# coding: utf-8

"""
    Serge API

    API documentation for Serge server  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2005Data(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'title': 'str',
        'initiated': 'bool',
        'short_name': 'str'
    }

    attribute_map = {
        'name': 'name',
        'title': 'title',
        'initiated': 'initiated',
        'short_name': 'shortName'
    }

    def __init__(self, name=None, title=None, initiated=None, short_name=None):  # noqa: E501
        """InlineResponse2005Data - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._title = None
        self._initiated = None
        self._short_name = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if title is not None:
            self.title = title
        if initiated is not None:
            self.initiated = initiated
        if short_name is not None:
            self.short_name = short_name

    @property
    def name(self):
        """Gets the name of this InlineResponse2005Data.  # noqa: E501


        :return: The name of this InlineResponse2005Data.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse2005Data.


        :param name: The name of this InlineResponse2005Data.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def title(self):
        """Gets the title of this InlineResponse2005Data.  # noqa: E501


        :return: The title of this InlineResponse2005Data.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this InlineResponse2005Data.


        :param title: The title of this InlineResponse2005Data.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def initiated(self):
        """Gets the initiated of this InlineResponse2005Data.  # noqa: E501


        :return: The initiated of this InlineResponse2005Data.  # noqa: E501
        :rtype: bool
        """
        return self._initiated

    @initiated.setter
    def initiated(self, initiated):
        """Sets the initiated of this InlineResponse2005Data.


        :param initiated: The initiated of this InlineResponse2005Data.  # noqa: E501
        :type: bool
        """

        self._initiated = initiated

    @property
    def short_name(self):
        """Gets the short_name of this InlineResponse2005Data.  # noqa: E501


        :return: The short_name of this InlineResponse2005Data.  # noqa: E501
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name):
        """Sets the short_name of this InlineResponse2005Data.


        :param short_name: The short_name of this InlineResponse2005Data.  # noqa: E501
        :type: str
        """

        self._short_name = short_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2005Data, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2005Data):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
