# coding: utf-8

"""
    Serge API

    API documentation for Serge server  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import serge_client
from serge_client.models.inline_response20015 import InlineResponse20015  # noqa: E501
from serge_client.rest import ApiException


class TestInlineResponse20015(unittest.TestCase):
    """InlineResponse20015 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20015(self):
        """Test InlineResponse20015"""
        # FIXME: construct object with mandatory attributes with example values
        # model = serge_client.models.inline_response20015.InlineResponse20015()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
