# coding: utf-8

"""
    Serge API

    API documentation for Serge server  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import serge_client
from serge_client.models.inline_response20011_data import InlineResponse20011Data  # noqa: E501
from serge_client.rest import ApiException


class TestInlineResponse20011Data(unittest.TestCase):
    """InlineResponse20011Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20011Data(self):
        """Test InlineResponse20011Data"""
        # FIXME: construct object with mandatory attributes with example values
        # model = serge_client.models.inline_response20011_data.InlineResponse20011Data()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
