# coding: utf-8

"""
    Serge API

    API documentation for Serge server  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import serge_client
from serge_client.api.database_operations_api import DatabaseOperationsApi  # noqa: E501
from serge_client.rest import ApiException


class TestDatabaseOperationsApi(unittest.TestCase):
    """DatabaseOperationsApi unit test stubs"""

    def setUp(self):
        self.api = DatabaseOperationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_all_dbs_get(self):
        """Test case for all_dbs_get

        Get all wargame names  # noqa: E501
        """
        pass

    def test_bulk_docs_dbname_put(self):
        """Test case for bulk_docs_dbname_put

        Bulk document update  # noqa: E501
        """
        pass

    def test_clear_all_delete(self):
        """Test case for clear_all_delete

        Clear all databases  # noqa: E501
        """
        pass

    def test_delete_db_name_delete(self):
        """Test case for delete_db_name_delete

        Delete database  # noqa: E501
        """
        pass

    def test_get_wargame_id_get(self):
        """Test case for get_wargame_id_get

        Get document for a specified wargame  # noqa: E501
        """
        pass

    def test_replicate_replicate_dbname_get(self):
        """Test case for replicate_replicate_dbname_get

        Replicate database  # noqa: E501
        """
        pass

    def test_wargame_dbname_logs_get(self):
        """Test case for wargame_dbname_logs_get

        Get logs for a specific database within a wargame  # noqa: E501
        """
        pass

    def test_wargame_dbname_logs_latest_get(self):
        """Test case for wargame_dbname_logs_latest_get

        Get the latest logs for a specific database within a wargame  # noqa: E501
        """
        pass

    def test_wargame_force_id_counter_get(self):
        """Test case for wargame_force_id_counter_get

        Get the message counter for a specified force in a wargame  # noqa: E501
        """
        pass

    def test_wargame_get(self):
        """Test case for wargame_get

        Retrieve all message documents for the specified wargame.  # noqa: E501
        """
        pass

    def test_wargame_last_doc_id_get(self):
        """Test case for wargame_last_doc_id_get

        Get the last document or documents since a specific ID  # noqa: E501
        """
        pass

    def test_wargame_last_get(self):
        """Test case for wargame_last_get

        Get the last wargame  # noqa: E501
        """
        pass

    def test_wargame_list_get(self):
        """Test case for wargame_list_get

        Get wargame list  # noqa: E501
        """
        pass

    def test_wargame_put(self):
        """Test case for wargame_put

        Update wargame  # noqa: E501
        """
        pass

    def test_wargame_turns_get(self):
        """Test case for wargame_turns_get

        Get game turns for a specified wargame  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
