# coding: utf-8

"""
    Serge API

    API documentation for Serge server  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import serge_client
from serge_client.api.file_management_api import FileManagementApi  # noqa: E501
from serge_client.rest import ApiException


class TestFileManagementApi(unittest.TestCase):
    """FileManagementApi unit test stubs"""

    def setUp(self):
        self.api = FileManagementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_icon_icon_get(self):
        """Test case for get_icon_icon_get

        Get icon  # noqa: E501
        """
        pass

    def test_save_icon_post(self):
        """Test case for save_icon_post

        Save icon  # noqa: E501
        """
        pass

    def test_save_logo_post(self):
        """Test case for save_logo_post

        Save a logo image  # noqa: E501
        """
        pass

    def test_tiles_folder_zyx_get(self):
        """Test case for tiles_folder_zyx_get

        Get tile image  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
