# coding: utf-8

"""
    Serge API

    API documentation for Serge server  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import serge_client
from serge_client.api.database_management_api import DatabaseManagementApi  # noqa: E501
from serge_client.rest import ApiException


class TestDatabaseManagementApi(unittest.TestCase):
    """DatabaseManagementApi unit test stubs"""

    def setUp(self):
        self.api = DatabaseManagementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_db_get(self):
        """Test case for delete_db_get

        Delete a database  # noqa: E501
        """
        pass

    def test_download_all_get(self):
        """Test case for download_all_get

        Download all databases  # noqa: E501
        """
        pass

    def test_download_wargame_get(self):
        """Test case for download_wargame_get

        Download wargame database  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
